print("Today's date?")
day = input()
print("Breakfast calories?")
breakfast = int(input())
print("Lunch calories?")
lunch = int(input())
print("Dinner calories?")
dinner = int(input())
print("Snack calories?")
snack = int(input())
print(f"Calorie content for {day}: {breakfast + lunch + dinner +snack}")